menu:
  Home: /
  Archives: /archives

widgets:
- search

cover:
  enable: true
  url: http://ww1.sinaimg.cn/large/6cea169fjw1edgyzma1xcj21kw16ohba.jpg
   
excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

addthis:
  enable: true
  pubid:
  facebook:
  twitter:
  google: true
  pinterest:

fancybox: true

google_analytics: UA-36877105-X
rss:

comment_provider: duoshuo

# Duoshuo comment
duoshuo:
  short_name: your_name

social:
  github: https://github.com/your_name
  weibo: http://weibo.com/your_name
  google_plus: 

auto_change:
  enable: true
